"""Add change_history table for audit logging

Revision ID: efbedfa0cf27
Revises: d0520053c523
Create Date: 2025-12-17 20:45:29.818644+08:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "efbedfa0cf27"
down_revision: str | Sequence[str] | None = "d0520053c523"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "change_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "entity_type",
            sa.String(length=50),
            nullable=False,
            comment="Entity type: invoice_line_item, campaign, line_item, comment",
        ),
        sa.Column(
            "entity_id",
            sa.Integer(),
            nullable=False,
            comment="ID of the modified entity",
        ),
        sa.Column(
            "old_value",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Previous values (null for creation)",
        ),
        sa.Column(
            "new_value",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            comment="New values after the change",
        ),
        sa.Column("changed_by_user_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["changed_by_user_id"], ["users.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("change_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_change_history_changed_by_user_id"),
            ["changed_by_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_change_history_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            "ix_change_history_entity", ["entity_type", "entity_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("change_history", schema=None) as batch_op:
        batch_op.drop_index("ix_change_history_entity")
        batch_op.drop_index(batch_op.f("ix_change_history_created_at"))
        batch_op.drop_index(batch_op.f("ix_change_history_changed_by_user_id"))

    op.drop_table("change_history")
    # ### end Alembic commands ###
