"""initial schema with campaigns, line_items, invoices

Revision ID: daa033267bcf
Revises:
Create Date: 2025-12-13 21:33:06.675626+08:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "daa033267bcf"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campaigns",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "invoices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campaign_id", name="uq_invoices_campaign_id"),
        comment="Challenge simplification: enforce 1 campaign : 1 invoice relationship",
    )
    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_invoices_campaign_id"), ["campaign_id"], unique=False
        )

    op.create_table(
        "line_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "booked_amount",
            sa.Numeric(precision=30, scale=15),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["campaign_id"], ["campaigns.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "campaign_id", "name", name="uq_line_items_campaign_id_name"
        ),
    )
    with op.batch_alter_table("line_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_line_items_campaign_id"), ["campaign_id"], unique=False
        )

    op.create_table(
        "invoice_line_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("invoice_id", sa.Integer(), nullable=False),
        sa.Column("line_item_id", sa.Integer(), nullable=False),
        sa.Column(
            "actual_amount",
            sa.Numeric(precision=30, scale=15),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "adjustments",
            sa.Numeric(precision=30, scale=15),
            server_default=sa.text("0"),
            nullable=False,
        ),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["invoice_id"], ["invoices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["line_item_id"], ["line_items.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "invoice_id",
            "line_item_id",
            name="uq_invoice_line_items_invoice_id_line_item_id",
        ),
    )
    with op.batch_alter_table("invoice_line_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_invoice_line_items_invoice_id"), ["invoice_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_invoice_line_items_line_item_id"),
            ["line_item_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("invoice_line_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invoice_line_items_line_item_id"))
        batch_op.drop_index(batch_op.f("ix_invoice_line_items_invoice_id"))

    op.drop_table("invoice_line_items")
    with op.batch_alter_table("line_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_line_items_campaign_id"))

    op.drop_table("line_items")
    with op.batch_alter_table("invoices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_invoices_campaign_id"))

    op.drop_table("invoices")
    op.drop_table("campaigns")
    # ### end Alembic commands ###
