"""Add password hash to users

Revision ID: d0520053c523
Revises: 3617dafa59d0
Create Date: 2025-12-16 21:24:14.582590+08:00

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d0520053c523"
down_revision: str | Sequence[str] | None = "3617dafa59d0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Pre-computed bcrypt hash for "password123" as default password for existing users
    default_hash = "$2b$12$4/jYBe2FhZ1HQJZhqhQ11uHTwscvdsd2XeIqv7rCJmmtTE4FcrPF."

    # Add column as nullable first
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("password_hash", sa.String(length=255), nullable=True)
        )

    # Set default value for existing rows
    op.execute(
        f"UPDATE users SET password_hash = '{default_hash}' WHERE password_hash IS NULL"
    )

    # Make column NOT NULL
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column("password_hash", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("password_hash")

    # ### end Alembic commands ###
